title: GitHub 博客探索的第一步
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: #"/flexible-jekyll"  the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
favicon: favicon.ico
# Author Settings
author: 鱼丸粗面 # add your name
author-img: handsome-cat.jpg # add your photo
about-author: 机器学习和 Python 的基情 # I am a web developer focusing on front-end development. Always hungry to keep learning.  add description
about-author: 缺个女朋友······ # I am a web developer focusing on front-end development. Always hungry to keep learning.  add description
twitter: TeemoNicolas # add your Twitter handle
facebook: # add your Facebook handle
github: lovesarmon # add your Github handle
linkedin: # add your Linkedin handle
email: yuwancumian666@gmail.com # add your Email address

# Disqus
discus-identifier: yuwancumian666 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
